CREATE TABLE fact_quest_participation (
    participation_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id         NUMBER NOT NULL,
    quest_id          NUMBER NOT NULL,
    time_id           NUMBER NOT NULL,
    duration_minutes  NUMBER,
    reward_points     NUMBER,

    CONSTRAINT fk_fqp_player
        FOREIGN KEY (player_id)
        REFERENCES dim_player(player_id),

    CONSTRAINT fk_fqp_quest
        FOREIGN KEY (quest_id)
        REFERENCES dim_quest(quest_id),

    CONSTRAINT fk_fqp_time
        FOREIGN KEY (time_id)
        REFERENCES dim_time(time_id)
);

--Task 1 : Add fact_quest_ratings table
CREATE TABLE fact_quest_ratings (
    rating_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id     NUMBER NOT NULL,
    quest_id      NUMBER NOT NULL,
    rating        NUMBER CHECK (rating IN (-1, 1)),
    time_id       NUMBER NOT NULL,

    CONSTRAINT fk_fqr_player
        FOREIGN KEY (player_id)
        REFERENCES dim_player(player_id),

    CONSTRAINT fk_fqr_quest
        FOREIGN KEY (quest_id)
        REFERENCES dim_quest(quest_id),

    CONSTRAINT fk_fqr_time
        FOREIGN KEY (time_id)
        REFERENCES dim_time(time_id)
);


CREATE TABLE fact_player_activity (
    activity_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id            NUMBER NOT NULL,
    time_id              NUMBER NOT NULL,
    quests_completed     NUMBER,
    total_duration       NUMBER,
    total_reward_points  NUMBER,

    CONSTRAINT fk_fpa_player
        FOREIGN KEY (player_id)
        REFERENCES dim_player(player_id),

    CONSTRAINT fk_fpa_time
        FOREIGN KEY (time_id)
        REFERENCES dim_time(time_id)
);  

--Task 2 done by naming the fact tables as per the naming convention